# Generated by Django 5.1.3 on 2024-11-23 14:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('farm_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('farm_name', models.CharField(max_length=255)),
                ('farm_size', models.FloatField()),
                ('farm_location', models.TextField()),
                ('image_urls', models.JSONField(blank=True, null=True)),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.farmer')),
            ],
        ),
    ]
