# Generated by Django 5.1.3 on 2024-11-23 14:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '__first__'),
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.buyer')),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.farm')),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(max_length=11)),
                ('cost', models.DecimalField(decimal_places=0, max_digits=10)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('order_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
                ('farmer_confirmation', models.IntegerField(blank=True, null=True)),
                ('buyer_confirmation', models.IntegerField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.buyer')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.farmer')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
